---
apiVersion: batch/v1
kind: Job
metadata:
  name: fastqc
spec:
  template:
    metadata:
      name: fastqc
    spec:
      containers:
      - name: fastqc
        image: fastqc
        command:
        restartPolicy: Never
        volumeMounts:
          -mountPath:
  